### PR TITLE
Use HEAD inject && lowered the mixin priority

### PR DESCRIPTION
**Pull request by VulpesStella**

### CODE REVIEW

**Comment by TropheusJ** [comment]
Unconditional head cancels are worse than overwrites. What is this trying to fix?

**Comment by Snownee** [comment]
Hello TropheusJ, I am happy to answer this question.

Basically we are making our own dripstone fluid lib for [Lychee mod](https://www.curseforge.com/minecraft/mc-mods/lychee-fabric), which will allow you to drain fluid from blocks, not only fluids. But the current implementation of the PointedDripstoneBlockMixin just completely eliminates the possibility to make mods compatible.

This PR intends to make things compatible, with minimal modification in dripstone fluid lib. If you have a more graceful way to do this, I'd appreciate it.

**Comment by TropheusJ** [comment]
Well the most graceful option is to not have 2 dripstone libraries. 

Otherwise, if your mixins are lower priority (higher number), they should work fine as long as they aren’t also overwrites.

**Comment by TropheusJ** [comment]
A PR adding the needed features to this API would be nice. If you don’t have time for a PR, tell me what’s needed and I can do it.

**Comment by Snownee** [comment]
It's hard to describe but I will try my best..

As you probably know we are working on a mod allows user to define in-world interactions. For example, a user can define block A as source block, which will make target block B becomes block C. Then, drop some items on ground or execute a command, etc. All in all, everything is very flexible.

First as all recipes are data-driven, all the blocks are possible to be the source block or the target block, we can't check if the block is a valid source by checking if the block has implemented an interface. Because the target block may not be non-solid, there should be a hook for us to check if a block is a valid target, rather than just the cauldron.

Finally, all these user-defined interactions should be at the highest priority, as users are allowed to use our mod to prevent built-in interactions, like lava farm.

Apologies my English is poor. If you have any trouble understanding them, I am willing to explain.

**Comment by TropheusJ** [comment]
A, B, and C is confusing me.
It seems A is the “cauldron” below the dripstone, and B is the block placed on top, like mud, which is converted into C, like clay. Right?

That’s probably not that bad to implement. Data-driving should be doable on your side, and priority should be manageable with an event.

**Comment by Snownee** [comment]
A is the block placed on top, B is the "cauldron"

**Comment by TropheusJ** [comment]
planning on a large refactor for 1.19.3, will try to get this in there.

**Pull request closed without merging**
